name: Deployment
run-name: ${{ github.actor }} is pushing changes to production

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Build and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PASSWORD }}
          CONNECTION_STRING: ${{ vars.EC2_CONNECTION_STRING }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${CONNECTION_STRING}'
          sudo docker build -t marketingapi https://github.com/fjensen21/marketingapi.git
          sudo docker rm -f marketingapi
