name: Deployment
run-name: ${{ github.actor }} is pushing changes to production

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o "StrictHostKeyChecking=no" -i ssh_key.pem ${{ vars.EC2_CONNECTION_STRING }}
          sudo docker build -t marketingapi https://github.com/fjensen21/marketingapi.git
          sudo docker rm -f marketingapi

      - name: Clean up SSH key
        run: |
          rm ssh_key.pem
