name: Deployment
run-name: ${{ github.actor }} is pushing changes to production

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          ssh -i ${{secrets.EC2_PASSWORD}} ${{secrets.EC2_CONNECTION_STRING}}
          sudo docker build -t marketingapi GIT_REPO_LINK
          sudo docker rm -f marketingapi https://github.com/fjensen21/marketingapi.git
