name: Deployment
run-name: ${{ github.actor }} is pushing changes to production

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Echo ENV Variables
        run: |
          echo "PASSWORD: ${{secrets.EC2_PASSWORD}}"
          echo "CONNECTION STR: $${{ vars.EC2_CONNECTION_STRING}}"
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          ssh -i <(echo ${{secrets.EC2_PASSWORD}}) ${{vars.EC2_CONNECTION_STRING}}
          sudo docker build -t marketingapi https://github.com/fjensen21/marketingapi.git
          sudo docker rm -f marketingapi
